In [59]:
import pandas as pd
import requests
import time

#for view dataset nicely
pd.set_option("display.max_columns", None)   # Show all columns
pd.set_option("display.width", None)         # Don't wrap columns
pd.set_option("display.width", 1000)

In [23]:
url = "https://f1-motorsport-data.p.rapidapi.com/schedule"

querystring = {"year":"2024"}

headers = {
	"x-rapidapi-key": "cc30b177f7msh2b0ba96cfd0d061p10144ejsna3cc2725a075",
	"x-rapidapi-host": "f1-motorsport-data.p.rapidapi.com",
	"Content-Type": "application/json"
}

# headers are necessary, if i not use it ,i got 401 status code which is unauthorized
response = requests.get(url, headers=headers,params=querystring)
print(response.status_code)

200

In the dataset , we have 24 items in year 2024. 
Each item contains 10 keys{like start,end, gprx,winner and more}  this are of nested dictionary->winner contains 4 more subpart{racer name, id,age,etc}

In [26]:
data=response.json()
print(type(data))   #data is of list type
# print(data)

<class 'list'>

In [40]:
print(data[0])

print('\n')
print(data[0]['startDate']) #gives only date
print(data[0]["winnerAthlete"]["name"])

{'startDate': '2025-03-14T01:30Z', 'endDate': '2025-03-16T04:00Z', 'featuredAthletes': 'featuredAthletes', 'status': {'id': '3', 'state': 'post', 'detail': 'Final'}, 'completed': True, 'gPrx': 'Louis Vuitton Australian GP', 'crct': 'Melbourne Grand Prix Circuit', 'evLink': '/f1/race/_/id/600052045', 'isPostponedOrCanceled': False, 'winnerAthlete': {'id': '5579', 'name': 'Lando Norris', 'flag': 'https://a.espncdn.com/i/teamlogos/countries/500/gbr.png', 'citizenship': 'Britain'}}


2025-03-14T01:30Z
Lando Norris

In [47]:
df = pd.json_normalize(data)  #use for nested dictionary 
# print(df)  #this is a dataframe

display(df)   #display gives good table to view,  'print' is not nice to view

            startDate            endDate  featuredAthletes  completed                                 gPrx                                crct                   evLink  isPostponedOrCanceled status.id status.state status.detail winnerAthlete.id winnerAthlete.name                                 winnerAthlete.flag winnerAthlete.citizenship
0   2025-03-14T01:30Z  2025-03-16T04:00Z  featuredAthletes       True          Louis Vuitton Australian GP        Melbourne Grand Prix Circuit  /f1/race/_/id/600052045                  False         3         post         Final             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
1   2025-03-21T03:30Z  2025-03-23T07:00Z  featuredAthletes       True                  Heineken Chinese GP      Shanghai International Circuit  /f1/race/_/id/600052046                  False         3         post         Final             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia
2   2025-04-04T02:30Z  2025-04-06T05:00Z  featuredAthletes       True                   Lenovo Japanese GP  Suzuka International Racing Course  /f1/race/_/id/600052047                  False         3         post         Final             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands
3   2025-04-11T11:30Z  2025-04-13T15:00Z  featuredAthletes       True                  Gulf Air Bahrain GP       Bahrain International Circuit  /f1/race/_/id/600052048                  False         3         post         Final             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia
4   2025-04-18T13:30Z  2025-04-20T17:00Z  featuredAthletes       True                 STC Saudi Arabian GP               Jeddah Street Circuit  /f1/race/_/id/600052049                  False         3         post         Final             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia
5   2025-05-02T16:30Z  2025-05-04T20:00Z  featuredAthletes       True                  Crypto.com Miami GP       Miami International Autodrome  /f1/race/_/id/600052050                  False         3         post         Final             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia
6   2025-05-16T11:30Z  2025-05-18T13:00Z  featuredAthletes       True  AWS Made in Italy Emilia Romagna GP       Autodromo Enzo e Dino Ferrari  /f1/race/_/id/600052051                  False         3         post         Final             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands
7   2025-05-23T11:30Z  2025-05-25T13:00Z  featuredAthletes       True                  Tag Heuer Monaco GP                   Circuit de Monaco  /f1/race/_/id/600052052                  False         3         post         Final             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
8   2025-05-30T11:30Z  2025-06-01T13:00Z  featuredAthletes       True                    Aramco Spanish GP                             Madring  /f1/race/_/id/600052053                  False         3         post         Final             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia
9   2025-06-13T17:30Z  2025-06-15T18:00Z  featuredAthletes       True                  Pirelli Canadian GP           Circuit Gilles-Villeneuve  /f1/race/_/id/600052054                  False         3         post         Final             5503     George Russell  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
10  2025-06-27T11:30Z  2025-06-29T13:00Z  featuredAthletes       True              MSC Cruises Austrian GP                       Red Bull Ring  /f1/race/_/id/600052055                  False         3         post         Final             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
11  2025-07-04T11:30Z  2025-07-06T14:00Z  featuredAthletes       True             Qatar Airways British GP                 Silverstone Circuit  /f1/race/_/id/600052056                  False         3         post         Final             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
12  2025-07-25T10:30Z  2025-07-27T13:00Z  featuredAthletes       True            Moët & Chandon Belgian GP        Circuit de Spa-Francorchamps  /f1/race/_/id/600052057                  False         3         post         Final             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia
13  2025-08-01T11:30Z  2025-08-03T13:00Z  featuredAthletes       True                  Lenovo Hungarian GP                         Hungaroring  /f1/race/_/id/600052058                  False         3         post         Final             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
14  2025-08-29T10:30Z  2025-08-31T13:00Z  featuredAthletes       True                    Heineken Dutch GP              Circuit Park Zandvoort  /f1/race/_/id/600052059                  False         3         post         Final             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia
15  2025-09-05T11:30Z  2025-09-07T13:00Z  featuredAthletes       True                   Pirelli Italian GP           Autodromo Nazionale Monza  /f1/race/_/id/600052060                  False         3         post         Final             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands
16  2025-09-19T08:30Z  2025-09-21T11:00Z  featuredAthletes       True          Qatar Airways Azerbaijan GP                   Baku City Circuit  /f1/race/_/id/600052101                  False         3         post         Final             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands
17  2025-10-03T09:30Z  2025-10-05T12:00Z  featuredAthletes       True      Singapore Airlines Singapore GP           Marina Bay Street Circuit  /f1/race/_/id/600052102                  False         3         post         Final             5503     George Russell  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
18  2025-10-17T17:30Z  2025-10-19T19:00Z  featuredAthletes       True         MSC Cruises United States GP             Circuit of the Americas  /f1/race/_/id/600052103                  False         3         post         Final             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands
19  2025-10-24T18:30Z  2025-10-26T20:00Z  featuredAthletes       True                       Mexico City GP        Autodromo Hermanos Rodriguez  /f1/race/_/id/600052104                  False         3         post         Final             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
20  2025-11-07T14:30Z  2025-11-09T17:00Z  featuredAthletes       True             MSC Cruises São Paulo GP          Autodromo Jose Carlos Pace  /f1/race/_/id/600052105                  False         3         post         Final             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain
21  2025-11-21T00:30Z  2025-11-23T04:00Z  featuredAthletes       True                Heineken Las Vegas GP            Las Vegas Street Circuit  /f1/race/_/id/600052106                  False         3         post         Final             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands
22  2025-11-28T13:30Z  2025-11-30T16:00Z  featuredAthletes       True               Qatar Airways Qatar GP        Losail International Circuit  /f1/race/_/id/600052107                  False         3         post         Final             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands
23  2025-12-05T09:30Z  2025-12-07T13:00Z  featuredAthletes       True          Etihad Airways Abu Dhabi GP                  Yas Marina Circuit  /f1/race/_/id/600052108                  False         3         post         Final             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands

In [52]:
df1 = pd.json_normalize(data)[['startDate','endDate','gPrx','crct','winnerAthlete.id','winnerAthlete.name','winnerAthlete.flag','winnerAthlete.citizenship','evLink','completed']]

display(df1)

            startDate            endDate                                 gPrx                                crct winnerAthlete.id winnerAthlete.name                                 winnerAthlete.flag winnerAthlete.citizenship                   evLink  completed
0   2025-03-14T01:30Z  2025-03-16T04:00Z          Louis Vuitton Australian GP        Melbourne Grand Prix Circuit             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052045       True
1   2025-03-21T03:30Z  2025-03-23T07:00Z                  Heineken Chinese GP      Shanghai International Circuit             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia  /f1/race/_/id/600052046       True
2   2025-04-04T02:30Z  2025-04-06T05:00Z                   Lenovo Japanese GP  Suzuka International Racing Course             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands  /f1/race/_/id/600052047       True
3   2025-04-11T11:30Z  2025-04-13T15:00Z                  Gulf Air Bahrain GP       Bahrain International Circuit             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia  /f1/race/_/id/600052048       True
4   2025-04-18T13:30Z  2025-04-20T17:00Z                 STC Saudi Arabian GP               Jeddah Street Circuit             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia  /f1/race/_/id/600052049       True
5   2025-05-02T16:30Z  2025-05-04T20:00Z                  Crypto.com Miami GP       Miami International Autodrome             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia  /f1/race/_/id/600052050       True
6   2025-05-16T11:30Z  2025-05-18T13:00Z  AWS Made in Italy Emilia Romagna GP       Autodromo Enzo e Dino Ferrari             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands  /f1/race/_/id/600052051       True
7   2025-05-23T11:30Z  2025-05-25T13:00Z                  Tag Heuer Monaco GP                   Circuit de Monaco             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052052       True
8   2025-05-30T11:30Z  2025-06-01T13:00Z                    Aramco Spanish GP                             Madring             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia  /f1/race/_/id/600052053       True
9   2025-06-13T17:30Z  2025-06-15T18:00Z                  Pirelli Canadian GP           Circuit Gilles-Villeneuve             5503     George Russell  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052054       True
10  2025-06-27T11:30Z  2025-06-29T13:00Z              MSC Cruises Austrian GP                       Red Bull Ring             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052055       True
11  2025-07-04T11:30Z  2025-07-06T14:00Z             Qatar Airways British GP                 Silverstone Circuit             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052056       True
12  2025-07-25T10:30Z  2025-07-27T13:00Z            Moët & Chandon Belgian GP        Circuit de Spa-Francorchamps             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia  /f1/race/_/id/600052057       True
13  2025-08-01T11:30Z  2025-08-03T13:00Z                  Lenovo Hungarian GP                         Hungaroring             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052058       True
14  2025-08-29T10:30Z  2025-08-31T13:00Z                    Heineken Dutch GP              Circuit Park Zandvoort             5752      Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...                 Australia  /f1/race/_/id/600052059       True
15  2025-09-05T11:30Z  2025-09-07T13:00Z                   Pirelli Italian GP           Autodromo Nazionale Monza             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands  /f1/race/_/id/600052060       True
16  2025-09-19T08:30Z  2025-09-21T11:00Z          Qatar Airways Azerbaijan GP                   Baku City Circuit             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands  /f1/race/_/id/600052101       True
17  2025-10-03T09:30Z  2025-10-05T12:00Z      Singapore Airlines Singapore GP           Marina Bay Street Circuit             5503     George Russell  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052102       True
18  2025-10-17T17:30Z  2025-10-19T19:00Z         MSC Cruises United States GP             Circuit of the Americas             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands  /f1/race/_/id/600052103       True
19  2025-10-24T18:30Z  2025-10-26T20:00Z                       Mexico City GP        Autodromo Hermanos Rodriguez             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052104       True
20  2025-11-07T14:30Z  2025-11-09T17:00Z             MSC Cruises São Paulo GP          Autodromo Jose Carlos Pace             5579       Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...                   Britain  /f1/race/_/id/600052105       True
21  2025-11-21T00:30Z  2025-11-23T04:00Z                Heineken Las Vegas GP            Las Vegas Street Circuit             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands  /f1/race/_/id/600052106       True
22  2025-11-28T13:30Z  2025-11-30T16:00Z               Qatar Airways Qatar GP        Losail International Circuit             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands  /f1/race/_/id/600052107       True
23  2025-12-05T09:30Z  2025-12-07T13:00Z          Etihad Airways Abu Dhabi GP                  Yas Marina Circuit             4665     Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...               Netherlands  /f1/race/_/id/600052108       True

In [53]:
#rename columns name
df1 = df1.rename(columns={
    'startDate': 'Start Date',
    'endDate': 'End Date',
    'gPrx': 'Grand Prix',
    'crct': 'Circuit',
    'winnerAthlete.id': 'Winner ID',
    'winnerAthlete.name': 'Winner',
    'winnerAthlete.flag': 'Flag',
    'winnerAthlete.citizenship': 'Country',
    'evLink': 'Event Link',
    'completed': 'Completed'
})

display(df1)

           Start Date           End Date                           Grand Prix                             Circuit Winner ID          Winner                                               Flag      Country               Event Link  Completed
0   2025-03-14T01:30Z  2025-03-16T04:00Z          Louis Vuitton Australian GP        Melbourne Grand Prix Circuit      5579    Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052045       True
1   2025-03-21T03:30Z  2025-03-23T07:00Z                  Heineken Chinese GP      Shanghai International Circuit      5752   Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...    Australia  /f1/race/_/id/600052046       True
2   2025-04-04T02:30Z  2025-04-06T05:00Z                   Lenovo Japanese GP  Suzuka International Racing Course      4665  Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052047       True
3   2025-04-11T11:30Z  2025-04-13T15:00Z                  Gulf Air Bahrain GP       Bahrain International Circuit      5752   Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...    Australia  /f1/race/_/id/600052048       True
4   2025-04-18T13:30Z  2025-04-20T17:00Z                 STC Saudi Arabian GP               Jeddah Street Circuit      5752   Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...    Australia  /f1/race/_/id/600052049       True
5   2025-05-02T16:30Z  2025-05-04T20:00Z                  Crypto.com Miami GP       Miami International Autodrome      5752   Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...    Australia  /f1/race/_/id/600052050       True
6   2025-05-16T11:30Z  2025-05-18T13:00Z  AWS Made in Italy Emilia Romagna GP       Autodromo Enzo e Dino Ferrari      4665  Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052051       True
7   2025-05-23T11:30Z  2025-05-25T13:00Z                  Tag Heuer Monaco GP                   Circuit de Monaco      5579    Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052052       True
8   2025-05-30T11:30Z  2025-06-01T13:00Z                    Aramco Spanish GP                             Madring      5752   Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...    Australia  /f1/race/_/id/600052053       True
9   2025-06-13T17:30Z  2025-06-15T18:00Z                  Pirelli Canadian GP           Circuit Gilles-Villeneuve      5503  George Russell  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052054       True
10  2025-06-27T11:30Z  2025-06-29T13:00Z              MSC Cruises Austrian GP                       Red Bull Ring      5579    Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052055       True
11  2025-07-04T11:30Z  2025-07-06T14:00Z             Qatar Airways British GP                 Silverstone Circuit      5579    Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052056       True
12  2025-07-25T10:30Z  2025-07-27T13:00Z            Moët & Chandon Belgian GP        Circuit de Spa-Francorchamps      5752   Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...    Australia  /f1/race/_/id/600052057       True
13  2025-08-01T11:30Z  2025-08-03T13:00Z                  Lenovo Hungarian GP                         Hungaroring      5579    Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052058       True
14  2025-08-29T10:30Z  2025-08-31T13:00Z                    Heineken Dutch GP              Circuit Park Zandvoort      5752   Oscar Piastri  https://a.espncdn.com/i/teamlogos/countries/50...    Australia  /f1/race/_/id/600052059       True
15  2025-09-05T11:30Z  2025-09-07T13:00Z                   Pirelli Italian GP           Autodromo Nazionale Monza      4665  Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052060       True
16  2025-09-19T08:30Z  2025-09-21T11:00Z          Qatar Airways Azerbaijan GP                   Baku City Circuit      4665  Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052101       True
17  2025-10-03T09:30Z  2025-10-05T12:00Z      Singapore Airlines Singapore GP           Marina Bay Street Circuit      5503  George Russell  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052102       True
18  2025-10-17T17:30Z  2025-10-19T19:00Z         MSC Cruises United States GP             Circuit of the Americas      4665  Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052103       True
19  2025-10-24T18:30Z  2025-10-26T20:00Z                       Mexico City GP        Autodromo Hermanos Rodriguez      5579    Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052104       True
20  2025-11-07T14:30Z  2025-11-09T17:00Z             MSC Cruises São Paulo GP          Autodromo Jose Carlos Pace      5579    Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052105       True
21  2025-11-21T00:30Z  2025-11-23T04:00Z                Heineken Las Vegas GP            Las Vegas Street Circuit      4665  Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052106       True
22  2025-11-28T13:30Z  2025-11-30T16:00Z               Qatar Airways Qatar GP        Losail International Circuit      4665  Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052107       True
23  2025-12-05T09:30Z  2025-12-07T13:00Z          Etihad Airways Abu Dhabi GP                  Yas Marina Circuit      4665  Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052108       True

###  Now we create database for years 2000-2025

In [ ]:


url = "https://f1-motorsport-data.p.rapidapi.com/schedule"
 
headers = {
	"x-rapidapi-key": "cc30b177f7msh2b0ba96cfd0d061p10144ejsna3cc2725a075",
	"x-rapidapi-host": "f1-motorsport-data.p.rapidapi.com",
	"Content-Type": "application/json"
}

all_dfs = []

for year in range(2000, 2026):
    querystring = {"year": year}
    response = requests.get(url, headers=headers, params=querystring)

    if response.status_code == 200:
        data = response.json()

        df = pd.json_normalize(data)[[
            'startDate',
            'endDate',
            'gPrx',
            'crct',
            'winnerAthlete.id',
            'winnerAthlete.name',
            'winnerAthlete.flag',
            'winnerAthlete.citizenship',
            'evLink',
            'completed'
        ]]

        df = df.rename(columns={
            'startDate': 'Start Date',
            'endDate': 'End Date',
            'gPrx': 'Grand Prix',
            'crct': 'Circuit',
            'winnerAthlete.id': 'Winner ID',
            'winnerAthlete.name': 'Winner',
            'winnerAthlete.flag': 'Flag',
            'winnerAthlete.citizenship': 'Country',
            'evLink': 'Event Link',
            'completed': 'Completed'
        })

        all_dfs.append(df)  #pehla dataframe bnao per year, and usko ek ek krke add kro
                            #option 2 -> pehle per year ka json bnao ,  and combinely saare json ko last me dataframe me convert krdo

    else:
        print(f"{year}: {response.status_code}")

    time.sleep(1)    # Avoid 429 rate-limit errors

# Combine all years into one DataFrame
final_df = pd.concat(all_dfs, ignore_index=True)

display(final_df)

In [68]:
url = "https://f1-motorsport-data.p.rapidapi.com/schedule" 

headers = {
	"x-rapidapi-key": "f0dd8dabbcmsh3a0d579e02cc78ap10a345jsn044559ee3c98",
	"x-rapidapi-host": "f1-motorsport-data.p.rapidapi.com",
	"Content-Type": "application/json"
}

all_data = []

for year in range(2000, 2026):
    response = requests.get(
        url,
        headers=headers,
        params={"year": year}
    )

    if response.status_code == 200:
        all_data.extend(response.json()) #ssare year ke data ko json file me daaldo then baad me ek saath dataframe me convert kr lena
    else:
        print(year, response.status_code)

    time.sleep(2)

final_df = (
    pd.json_normalize(all_data)[[
        'startDate',
        'endDate',
        'gPrx',
        'crct',
        'winnerAthlete.id',
        'winnerAthlete.name',
        'winnerAthlete.flag',
        'winnerAthlete.citizenship',
        'evLink',
        'completed'
    ]]
    .rename(columns={
        'startDate': 'Start Date',
        'endDate': 'End Date',
        'gPrx': 'Grand Prix',
        'crct': 'Circuit',
        'winnerAthlete.id': 'Winner ID',
        'winnerAthlete.name': 'Winner',
        'winnerAthlete.flag': 'Flag',
        'winnerAthlete.citizenship': 'Country',
        'evLink': 'Event Link',
        'completed': 'Completed'
    })
)

display(final_df)

2010 500
2018 500

            Start Date           End Date                   Grand Prix                        Circuit Winner ID              Winner                                               Flag      Country               Event Link  Completed
0    2000-03-12T05:00Z  2000-03-12T05:00Z                Australian GP   Melbourne Grand Prix Circuit       300  Michael Schumacher  https://a.espncdn.com/i/teamlogos/countries/50...  Switzerland       /f1/race/_/id/3716       True
1    2000-03-26T05:00Z  2000-03-26T05:00Z                 Brazilian GP     Autodromo Jose Carlos Pace       300  Michael Schumacher  https://a.espncdn.com/i/teamlogos/countries/50...  Switzerland       /f1/race/_/id/3717       True
2    2000-04-09T04:00Z  2000-04-09T04:00Z                San Marino GP  Autodromo Enzo E Dino Ferrari       300  Michael Schumacher  https://a.espncdn.com/i/teamlogos/countries/50...  Switzerland       /f1/race/_/id/3718       True
3    2000-04-23T04:00Z  2000-04-23T04:00Z                   British GP            Silverstone Circuit       304     David Coulthard  https://a.espncdn.com/i/teamlogos/countries/50...      Britain       /f1/race/_/id/3719       True
4    2000-05-07T04:00Z  2000-05-07T04:00Z                   Spanish GP                        Madring       290       Mika Hakkinen  https://a.espncdn.com/i/teamlogos/countries/50...      Finland       /f1/race/_/id/3720       True
..                 ...                ...                          ...                            ...       ...                 ...                                                ...          ...                      ...        ...
460  2025-10-24T18:30Z  2025-10-26T20:00Z               Mexico City GP   Autodromo Hermanos Rodriguez      5579        Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052104       True
461  2025-11-07T14:30Z  2025-11-09T17:00Z     MSC Cruises São Paulo GP     Autodromo Jose Carlos Pace      5579        Lando Norris  https://a.espncdn.com/i/teamlogos/countries/50...      Britain  /f1/race/_/id/600052105       True
462  2025-11-21T00:30Z  2025-11-23T04:00Z        Heineken Las Vegas GP       Las Vegas Street Circuit      4665      Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052106       True
463  2025-11-28T13:30Z  2025-11-30T16:00Z       Qatar Airways Qatar GP   Losail International Circuit      4665      Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052107       True
464  2025-12-05T09:30Z  2025-12-07T13:00Z  Etihad Airways Abu Dhabi GP             Yas Marina Circuit      4665      Max Verstappen  https://a.espncdn.com/i/teamlogos/countries/50...  Netherlands  /f1/race/_/id/600052108       True

[465 rows x 10 columns]

In [71]:

final_df.to_csv("f1_schedule_2000_2025.csv", index=False)
import os

print(os.getcwd())           # Shows the current working directory

C:\Users\hp